package com.factory.core.tracking

import android.content.Context
import com.factory.core.common.EnvironmentConfig
import com.factory.core.logging.Logger
import dagger.hilt.android.qualifiers.ApplicationContext
import java.time.Instant
import java.time.format.DateTimeFormatter
import javax.inject.Inject
import javax.inject.Singleton

private const val TAG = "InfinityForgeMetadata"

/**
 * Non-identity envelope metadata — everything in schema/event-envelope.yaml and
 * schema/metric-envelope.yaml except `event`/`metric_name`/`properties`/`dimensions`
 * (per-call) and `user_id`/`anonymous_id` (identity state — see [InfinityForgeIdentity]).
 * Field ownership matches specification/metadata.md: `app_id`/`app_version` are read
 * from this device's own [android.content.pm.PackageInfo] (the Android-native
 * equivalent of Swift reading `Bundle.main`/RN reading `expo-application` — no core
 * module reads `BuildConfig` directly, see `AppModule`'s own doc comment);
 * `environment` is derived from the injected [EnvironmentConfig] (app-owned, sourced
 * from `BuildConfig.ENVIRONMENT_NAME` at the `app` module's composition root);
 * `platform`/`sdk_name`/`sdk_version`/`timestamp` are generated by this adapter.
 */
@Singleton
class InfinityForgeMetadata @Inject constructor(
    @ApplicationContext private val context: Context,
    environmentConfig: EnvironmentConfig,
    private val logger: Logger,
) {
    companion object {
        /** Identifies this adapter as the Kotlin implementation of the contract,
         * distinct from a React Native or Swift adapter that might run on a different
         * `platform` — specification/metadata.md's "Why sdk_name exists". */
        const val SDK_NAME = "kotlin"

        /** This adapter's own release, per specification/versioning.md's
         * `sdk_version` — distinct from the contract version it implements
         * ([InfinityForgeContractVersion]) and from the host app's own `app_version`. */
        const val SDK_VERSION = "1.0.0"

        /** specification/conventions.md: ISO 8601 UTC with a "Z" suffix, captured at
         * the moment the operation is invoked. `DateTimeFormatter.ISO_INSTANT` already
         * produces exactly that shape for a UTC `Instant` and, unlike
         * `SimpleDateFormat`, is immutable and thread-safe — safe to share as a
         * constant rather than allocating one per call. */
        fun timestamp(now: Instant = Instant.now()): String = DateTimeFormatter.ISO_INSTANT.format(now)
    }

    /** This adapter is Android-only, so `platform` has exactly one possible value here
     * — unlike a cross-platform adapter, there is no runtime OS switch to perform. */
    fun platform(): InfinityForgePlatform = InfinityForgePlatform.ANDROID

    /**
     * Maps this factory's own [EnvironmentConfig.name] (one of `"dev"`/`"staging"`/
     * `"prod"` — `app/build.gradle.kts`'s three product flavors, each an explicit,
     * build-tooling-supplied `ENVIRONMENT_NAME` `buildConfigField`) onto the
     * contract's three-valued `environment`. This is an *explicit configured value*,
     * not the narrower "environment fallback" exception in specification/metadata.md
     * — every flavor always sets `ENVIRONMENT_NAME`, so the `else` branch below should
     * never fire in a correctly configured build; it exists only as the same
     * defensive, diagnostic-surfacing, safer-default (`production`) fallback that
     * exception describes, for a value this factory does not (yet) recognize.
     */
    fun environment(): InfinityForgeEnvironment = when (environmentName) {
        "dev" -> InfinityForgeEnvironment.DEVELOPMENT
        "staging" -> InfinityForgeEnvironment.PREVIEW
        "prod" -> InfinityForgeEnvironment.PRODUCTION
        else -> {
            logger.warn(
                TAG,
                "InfinityForge Tracking: EnvironmentConfig.name was \"$environmentName\", which this " +
                    "adapter does not recognize; falling back to production " +
                    "(specification/metadata.md's environment fallback exception).",
            )
            InfinityForgeEnvironment.PRODUCTION
        }
    }

    private val environmentName = environmentConfig.name

    private val packageInfo by lazy {
        @Suppress("DEPRECATION") // getPackageInfo(String, Int) is the min-SDK-safe overload this factory targets.
        context.packageManager.getPackageInfo(context.packageName, 0)
    }

    private val appId: String get() = context.packageName

    private val appVersion: String get() = packageInfo.versionName ?: "unknown"

    /** The metadata fields shared, unchanged, by every event and metric envelope built
     * in one call — mirrors the reference Swift implementation's `Base` struct and the
     * reference RN implementation's `buildBaseMetadata()`, reused (never redefined)
     * for both envelope kinds. */
    data class Base(
        val appId: String,
        val appVersion: String,
        val environment: InfinityForgeEnvironment,
        val platform: InfinityForgePlatform,
        val sdkName: String,
        val sdkVersion: String,
    )

    fun base(): Base = Base(
        appId = appId,
        appVersion = appVersion,
        environment = environment(),
        platform = platform(),
        sdkName = SDK_NAME,
        sdkVersion = SDK_VERSION,
    )
}
